[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 1
option_as_alt = "Both"

[font]
# normal.family = "0XProto Nerd Font Mono"
# normal.family = "Liga SFMono Nerd Font"
# normal.family = "FiraCode Nerd Font"
normal.family = "MesloLGS Nerd Font"
size = 16

[cursor]
style.shape = "Block"
style.blinking = "On"
unfocused_hollow = false

[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[scrolling]
history = 100000
